TestingSystem-master/InternetApp/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using InternetApp.Filters;
using InternetApp.Models;
using InternetApp.Models.ModelLogick;


namespace InternetApp.Controllers
{
    public class TestsController : Controller
    {

        private Model testModel = new Model();
        private int counter = 0;

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Counter = ++counter;
            // Необходимо узнать, аутентифицирован ли пользователь
            if (WebSecurity.IsAuthenticated)
            {
                // формируем список тестов для зарегистрированных пользователей
                return View(testModel.ListOfTestBlocks);
            }
            else
            {
                // тут будем выдавать страницу с информацией об ошибке
                return View("ErrorPage");
            }
        }

    }
}

TestingSystem-master/InternetApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

    <html lang="en">

        <head>
            <meta charset="utf-8" />
            <title>@ViewBag.Title - TestingSystem</title>
            <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
            <meta name="viewport" content="width=device-width" />
            @Styles.Render("~/Content/css")
            @Scripts.Render("~/bundles/modernizr")
        </head>


        <body>



            <div id="wrapper">

                <header>

                    <div class="content-wrapper">
                        <div class="float-left">
                            <p class="site-title">@Html.ActionLink("Система тестирования", "Index", "Home")</p>
                        </div>
                        <div class="float-right">
                            <section id="login">
                                @Html.Partial("_LoginPartial")
                            </section>
                            <nav>
                                <ul id="menu">
                                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                                    <li>@Html.ActionLink("Тестирование", "Index", "Tests")</li>
                                    <li>@Html.ActionLink("О нас", "About", "Home")</li>
                                    <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
                                </ul>
                            </nav>
                        </div>
                    </div>


                </header>



                <div id="body">



                    @RenderSection("featured", required: false)

                    <section class="content-wrapper main-content clear-fix">


                        @RenderBody()

                    </section>
                </div>
            </div>







            <footer>
                <div class="content-wrapper">
                    <div class="float-left">
                        <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                    </div>
                </div>
            </footer>


            @Scripts.Render("~/bundles/jquery")
            @RenderSection("scripts", required: false)
   
</body>

  
</html>